# Honeypot's Config file

database:
    type: sqlite
    uri: sql/honeypot.db
    user: test
    password: testpw

ldap:
    uri: 127.0.0.1
    port: 386
    base: dc=honeypot,dc=com
    user: cn=admin,dc=honeypot,dc=com
    password: admin_ldap
    base_object: ou=fake user,dc=honeypot,dc=com

broker_check_interval: 60 #seconds
inspector_interval: 60

log:
    level: DEBUG 
    file: loghoneypot.log #where logs are saved

inspector:
    logpath: files/log.test
    filter: files/regex.filter
    command: iptables
    bantime: 3600

