# Honeypot's Config file

database:
    type: sqlite
    uri: sql/honeypot.db
    user: test
    password: testpw
    check_interval: 60 #seconds broker interval

ldap:
    uri: 127.0.0.1
    port: 386
    base: dc=honeypot,dc=com
    user: cn=admin,dc=honeypot,dc=com
    password: admin_ldap
    base_object: ou=fake user,dc=honeypot,dc=com
    check_interval: 60 #seconds broker interval
#inspector_interval: 60

log:
    level: DEBUG 
    file: files/loghoneypot.log #where logs are saved

inspector:
    logfile: files/log.test
    regex: files/regex.filter
    command: iptables
    bantime: 3600 # not implemented
    check_interval: 60

