# Honeypot's Config file

database:
    host: 10.0.3.132
    user: honey
    password: 123456
    port: 5432
    db_name: honeypot_db
    check_interval: 60 #seconds broker interval

ldap:
    host: 10.0.3.132
    port: 389
    base: dc=honeypot,dc=com
    user: cn=admin,dc=honeypot,dc=com
    password: ubuntu
    base_object: ou=fake_user,dc=honeypot,dc=com
#inspector_interval: 60

log:
    level: DEBUG 
    file: files/loghoneypot.log #where logs are saved

inspector:
    logfile: files/log.test
    regex: files/regex.filter
    command: iptables
    bantime: 3600 # not implemented
    check_interval: 60

